version: '3.1'

services:
  
  mongo:
    container_name: morsley_mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: john
      MONGO_INITDB_ROOT_PASSWORD: morsley   
      
  mongo-express:
    container_name: morsley_mongo_admin
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: john
      ME_CONFIG_MONGODB_ADMINPASSWORD: morsley
      ME_CONFIG_MONGODB_URL: mongodb://john:morsley@mongo:27017/
    depends_on:
      - mongo